# Generated by Django 3.1.7 on 2021-07-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('V', 'VOUCHERS'), ('P', 'PACKAGES')], max_length=2)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
