# Generated by Django 3.1.7 on 2021-07-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='items',
        ),
    ]
