# Generated by Django 3.1.7 on 2021-09-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210804_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.IntegerField()),
                ('messages', models.TextField()),
            ],
        ),
    ]
